/* Local educational data. Replace this layer with a server API when needed.
   Never place private API keys in this file or any browser-delivered file. */
const DATA = {
  providers: [
    {name:'OpenAI',icon:'◎',color:'#83e4b1',className:'green',ecosystem:'ChatGPT & OpenAI API',tagline:'General intelligence. Everyday applications.',tags:['Multimodal','Developer ecosystem','Reasoning'],platform:'OpenAI API',agents:'Tool-connected application workflows',source:'https://openai.com/index/hello-gpt-4o/',focus:{Coding:'Code generation and debugging assistance.',Reasoning:'Problem-solving through natural language; verify conclusions.',Agents:'Applications can coordinate model output with external tools.',Multimodal:'Text, vision, and audio research in the GPT-4o announcement.',Enterprise:'Evaluate data handling, deployment controls, and cost for your organization.',Research:'Research toward general-purpose AI systems.'}},
    {name:'Anthropic',icon:'AⅠ',color:'#e8ad8d',className:'orange',ecosystem:'Claude & Anthropic API',tagline:'Helpful intelligence. Thoughtful by design.',tags:['Coding','Long context','Safety research'],platform:'Anthropic API',agents:'Tool use with application-managed permissions',source:'https://www.anthropic.com/news/claude-3-5-sonnet',focus:{Coding:'Claude 3.5 Sonnet was introduced with coding-focused capabilities.',Reasoning:'Analysis of complex instructions and documents.',Agents:'Tool-using workflows require orchestration and human controls.',Multimodal:'Text and image understanding in the June 2024 snapshot.',Enterprise:'Assess access controls and deployment options against your needs.',Research:'Alignment, interpretability, and model behavior research.'}},
    {name:'Google Gemini',icon:'✦',color:'#a9a1ff',className:'purple',ecosystem:'Gemini & Google AI',tagline:'Native multimodality. Connected intelligence.',tags:['Multimodal','Long context','Google ecosystem'],platform:'Google AI / Vertex AI',agents:'Model and tool integration in application workflows',source:'https://blog.google/innovation-and-ai/products/google-gemini-next-generation-model-february-2024/',focus:{Coding:'Analyze code and assist with software tasks.',Reasoning:'Reason over long inputs; results still need validation.',Agents:'Combine models with tools through an application layer.',Multimodal:'Gemini 1.5 explored text, image, audio, and video inputs.',Enterprise:'Consider Google Cloud integration and deployment requirements.',Research:'Long-context and multimodal model research.'}}
  ],
  models:[
    {id:'gpt4o',provider:'OpenAI',name:'GPT-4o',date:'2024-05-13',purpose:'Multimodal assistant',context:'Check version-specific documentation',input:'Text and images at initial API launch',output:'Text at initial API launch',reasoning:'General problem-solving',coding:'Code assistance',tools:'Application integration; check version docs',agents:'Requires external orchestration',api:'Historical launch availability; current status not tracked',best:'Exploring multimodal assistant design',limits:'May hallucinate; launch features differed by interface',source:0},
    {id:'sonnet35',provider:'Anthropic',name:'Claude 3.5 Sonnet',date:'2024-06-20',purpose:'Coding and analysis',context:'200K tokens at launch',input:'Text and images',output:'Text',reasoning:'General reasoning and analysis',coding:'Code generation and debugging',tools:'Tool use through application integration',agents:'Requires external orchestration',api:'Historical launch availability; current status not tracked',best:'Studying code and document workflows',limits:'Can make errors; large context does not ensure recall',source:1},
    {id:'gemini15',provider:'Google Gemini',name:'Gemini 1.5 Pro',date:'2024-02-15',purpose:'Long-context multimodal understanding',context:'128K standard; 1M experimental preview at announcement',input:'Text, images, audio, video',output:'Text',reasoning:'Reasoning over multimodal inputs',coding:'Code analysis and assistance',tools:'Check version-specific integration docs',agents:'Requires external orchestration',api:'Limited preview at announcement; current status not tracked',best:'Studying long-context analysis',limits:'Preview limits applied; long inputs can increase latency',source:2}
  ],
  scenarios:[
    ['AI personal agents','Assistants could coordinate research, draft emails, prepare schedules, analyze data, and plan work. Sensitive actions would still need explicit permission.'],
    ['Agentic software development','Developers may spend more time on requirements, architecture, testing, security, and reviewing generated changes. Reliable evaluation becomes central.'],
    ['AI-native companies','Small teams could automate more operations. Accountability, customer trust, and robust processes would remain essential.'],
    ['Personalized education','Tutors could adapt explanations and practice to each learner. Educators would still guide motivation, quality, and safeguarding.'],
    ['AI + robotics','Models may connect to physical machines more often. Reliability, hardware cost, and real-world safety could constrain adoption.'],
    ['Multi-agent systems','Specialist research, planning, coding, testing, security, and deployment agents could collaborate under human supervision.'],
    ['An AI operating layer','People may state an intention while AI coordinates several applications. Permissions and recoverable actions would be essential.'],
    ['Human + AI teams','Humans contribute judgment, responsibility, creativity, communication, and domain knowledge. AI could assist with generation, search, analysis, and repeated tasks.']
  ],
  levels:[
    ['Foundations',['HTML','CSS','JavaScript','TypeScript','Git','GitHub','HTTP','REST APIs','Data Structures','Algorithms'],'Build an accessible, responsive app that fetches and validates public data.'],
    ['Application development',['Browser APIs','Node.js','Databases','Authentication','Testing'],'Build a secure CRUD application with tests. Frameworks are optional; understand the underlying platform.'],
    ['Cloud',['Docker','CI/CD','Linux','Cloud','Serverless','Monitoring'],'Deploy a small service, add logging, and practice recovering from a failed deployment.'],
    ['AI development',['Python','LLM API','Prompt Engineering','Structured Outputs','Embeddings','Vector Search','RAG'],'Build a document assistant that cites its sources and handles missing evidence.'],
    ['AI engineering',['Tool Calling','Agents','Memory','Model Routing','Evaluation','Observability','Guardrails'],'Create a bounded tool workflow with approval gates, logs, and an evaluation set.'],
    ['Advanced AI systems',['Multi-Agent Systems','MCP','AI Security','Model Evaluation','Human-in-the-loop','System Design'],'Threat-model a tool-using system and measure how it fails before expanding permissions.'],
    ['2030 engineer',['Problem Solving','Architecture','Domain Expertise','AI Orchestration','Security','Product Thinking','Communication','Leadership'],'Explain a system tradeoff, own its results, and solve a real user problem.']
  ],
  skills:['HTML','CSS','JavaScript','TypeScript','Git','HTTP','Node.js','Python','SQL','Docker','Cloud','LLM API','RAG','Agents','MCP','Testing','System Design','Security'],
  roleSkills:{Frontend:['HTML','CSS','JavaScript','TypeScript','Git','HTTP','Testing','LLM API','Security'],Backend:['JavaScript','Node.js','SQL','HTTP','Testing','Docker','Security','System Design','LLM API'],'Full Stack':['HTML','CSS','JavaScript','Node.js','SQL','Testing','Security','System Design','LLM API'],Mobile:['JavaScript','TypeScript','HTTP','Git','Testing','Security','LLM API'],DevOps:['Git','Docker','Cloud','Testing','Security','System Design','Python'],Data:['Python','SQL','Git','Testing','LLM API','RAG','Security']},
  agents:[
    ['Research Agent','Find evidence and record sources.','Question and approved sources','Cited findings and uncertainty notes','Browser, document search','Check source reliability and private-data boundaries.'],
    ['Planning Agent','Break a goal into bounded, reviewable tasks.','Requirements and research','Task plan and acceptance criteria','Issue tracker, documents','Approve scope, dependencies, and success criteria.'],
    ['Coding Agent','Draft implementation changes.','Approved plan and repository context','Patch and implementation notes','Editor, terminal, repository','Review code before merge; restrict credentials.'],
    ['Testing Agent','Check expected behavior and failure paths.','Patch and acceptance criteria','Test cases and failure report','Test runner, sandbox','Verify that tests measure the actual requirement.'],
    ['Security Agent','Inspect changes for security risks.','Code diff and threat model','Risk report and suggested fixes','Static analysis, dependency audit','A human decides whether residual risk is acceptable.'],
    ['Documentation Agent','Explain system behavior and maintenance.','Reviewed implementation and decisions','Guides and change notes','Documentation repository','Check accuracy and remove sensitive information.']
  ],
  team:['Researcher','Planner','Frontend Developer','Backend Developer','Database Engineer','Tester','Security Reviewer','DevOps Engineer','Documentation Writer'],
  jobs:[
    ['Software Developer','High','Drafting boilerplate and routine code','Architecture and product judgment','Testing, system design, AI review','Build reliable AI-enabled applications.'],
    ['UI Developer','High','Layout drafts and repetitive styling','Accessibility and interaction quality','Browser APIs, accessibility, design systems','Prototype and validate interfaces faster.'],
    ['QA Engineer','High','Generating repetitive test cases','Risk analysis and exploratory testing','Evaluation, automation, test design','Evaluate AI behavior and failure modes.'],
    ['Data Analyst','High','Initial queries and summary drafts','Causal reasoning and domain context','SQL, statistics, data validation','Build verifiable analysis workflows.'],
    ['Customer Support','High','Routine ticket triage and answer drafts','Empathy and complex resolution','Knowledge management, escalation design','Design helpful support automation.'],
    ['Content Creation','High','Drafts, variations, and repurposing','Original reporting and editorial judgment','Fact checking, creative direction','Develop stronger editorial workflows.'],
    ['Project Management','Moderate','Status summaries and schedule drafts','Negotiation and accountability','Workflow design, communication','Coordinate human and AI contributors.'],
    ['Cybersecurity','Moderate','Alert summaries and initial triage','Adversarial thinking and incident decisions','AI security, threat modeling','Protect AI-connected systems.'],
    ['DevOps','Moderate','Runbook drafts and log summaries','Reliability and incident ownership','Observability, cloud, automation','Operate model-based services safely.'],
    ['Education','Moderate','Practice material and lesson drafts','Mentoring and learner wellbeing','Assessment design, AI literacy','Create supervised adaptive learning.'],
    ['Design','Moderate','Variants and initial explorations','Taste, user research, and context','Research, prototyping, accessibility','Design trustworthy AI interactions.'],
    ['Marketing','High','Copy variations and report drafts','Positioning and customer understanding','Experimentation, analytics','Test creative ideas with better evidence.']
  ],
  newRoles:[
    ['AI Application Engineer','Integrates models into useful products.','JavaScript, APIs, testing','Browser APIs, server runtimes'],['Agent Engineer','Builds bounded tool-using workflows.','Tool calling, evaluation, permissions','JavaScript, Python, JSON Schema'],['AI Automation Engineer','Connects repeatable business processes.','APIs, workflow design, monitoring','HTTP, queues, SQL'],['LLM Engineer','Improves model-driven application behavior.','Evaluation, retrieval, data quality','Python, embeddings, vector search'],['AI Platform Engineer','Provides shared model infrastructure.','Cloud, reliability, access controls','Containers, metrics, model gateways'],['AI Security Engineer','Protects AI systems and their tools.','Threat modeling, isolation, auditing','Sandboxes, policy engines'],['AI Evaluation Engineer','Measures quality and failure cases.','Statistics, test design, domain knowledge','Python, evaluation datasets'],['AI Product Engineer','Turns user needs into AI features.','Product judgment, UX, engineering','Web APIs, analytics'],['AI Integration Specialist','Connects AI with existing systems.','Authentication, APIs, data mapping','HTTP, OAuth, SQL'],['AI Governance Specialist','Defines controls and accountability.','Policy, risk assessment, documentation','Audit logs, risk registers'],['Human-AI Interaction Designer','Designs understandable AI experiences.','Research, accessibility, interaction design','Prototypes, usability testing'],['AI Infrastructure Engineer','Operates compute and inference services.','Networking, cloud, performance','Linux, containers, monitoring'],['Synthetic Data Engineer','Creates and validates generated datasets.','Statistics, privacy, data evaluation','Python, SQL, validation pipelines'],['AI Workflow Architect','Designs supervised end-to-end workflows.','System design, domain expertise, reliability','Architecture diagrams, event systems']
  ]
};
